import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { UserSearch, CheckCircle2, AlertCircle, Plus, ArrowRight } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../contexts/AuthContext'
import { PageHeader } from '../../components/ui/PageHeader'
import { FormField } from '../../components/ui/FormField'
import { Spinner } from '../../components/ui/Spinner'

interface NoteEntry { type: 'vitals' | 'injuries' | 'treatment' | 'general'; content: string }

const NOTE_TYPES = [
  { value: 'vitals',    label: 'Vitals' },
  { value: 'injuries',  label: 'Injuries' },
  { value: 'treatment', label: 'Treatment' },
  { value: 'general',   label: 'General' },
] as const

export function RegisterUnidentified() {
  const { profile, user } = useAuth()
  const navigate = useNavigate()

  const [form, setForm] = useState({
    placeholder_name:        '',
    approx_age:              '',
    approx_sex:              '',
    distinguishing_features: '',
  })
  const [notes, setNotes] = useState<NoteEntry[]>([
    { type: 'vitals', content: '' },
  ])
  const [busy,     setBusy]     = useState(false)
  const [apiError, setApiError] = useState('')
  const [result,   setResult]   = useState<{ mrn: string; id: string } | null>(null)

  const addNote = () => setNotes(n => [...n, { type: 'general', content: '' }])
  const removeNote = (i: number) => setNotes(n => n.filter((_, idx) => idx !== i))
  const setNote = (i: number, key: keyof NoteEntry, val: string) =>
    setNotes(n => n.map((note, idx) => idx === i ? { ...note, [key]: val } : note))

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!profile?.hospital_id || !user) return
    setBusy(true)
    setApiError('')
    try {
      // 1. Insert temporary record — MRN generated by DB trigger
      const { data: record, error: recErr } = await supabase
        .from('temporary_records')
        .insert({
          hospital_id:             profile.hospital_id as string,
          placeholder_name:        form.placeholder_name || 'Unidentified',
          approx_age:              form.approx_age ? parseInt(form.approx_age) : null,
          approx_sex:              form.approx_sex || null,
          distinguishing_features: form.distinguishing_features || null,
          created_by:              user.id,
        } as never)
        .select('id, mrn')
        .single()

      if (recErr || !record) throw new Error(recErr?.message ?? 'Failed to create record.')
      const rec = record as { id: string; mrn: string }

      // 2. Attach non-empty notes
      const filledNotes = notes.filter(n => n.content.trim())
      for (const note of filledNotes) {
        await supabase.from('clinical_notes').insert({
          record_id:   rec.id,
          record_type: 'temporary',
          hospital_id: profile.hospital_id as string,
          note_type:   note.type,
          content:     note.content,
          author_id:   user.id,
        } as never)
      }

      // 3. Audit log
      await supabase.from('audit_log').insert({
        hospital_id:     profile.hospital_id as string,
        event_type:      'temporary_record_created',
        actor_id:        user.id,
        record_ref:      rec.id,
        payload_summary: { mrn: rec.mrn, notes_attached: filledNotes.length },
      } as never)

      setResult({ mrn: rec.mrn, id: rec.id })
    } catch (err) {
      setApiError(err instanceof Error ? err.message : 'An unexpected error occurred.')
    } finally {
      setBusy(false)
    }
  }

  if (result) {
    return (
      <div className="max-w-lg mx-auto py-20 text-center animate-slide-up">
        <div className="w-16 h-16 rounded-2xl bg-teal-50 border border-teal-200 flex items-center justify-center mx-auto mb-6">
          <CheckCircle2 size={32} className="text-teal-600" />
        </div>
        <h2 className="text-2xl font-serif text-charcoal-900 mb-2">Record created</h2>
        <p className="text-charcoal-500 text-sm mb-4">Temporary record is ready. Clinical notes can be added at any time.</p>
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-teal-50 border border-teal-200 mb-8">
          <span className="text-xs text-teal-600 font-medium">MRN</span>
          <span className="font-mono text-lg font-semibold text-teal-800">{result.mrn}</span>
        </div>
        <div className="flex gap-3 justify-center">
          <button
            className="btn-secondary"
            onClick={() => { setResult(null); setForm({ placeholder_name: '', approx_age: '', approx_sex: '', distinguishing_features: '' }); setNotes([{ type: 'vitals', content: '' }]) }}
          >
            Register another
          </button>
          <button
            className="btn-primary flex items-center gap-2"
            onClick={() => navigate(`/hospital/identify/${result.id}`)}
          >
            Start identification <ArrowRight size={15} />
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-2xl mx-auto animate-fade-in">
      <PageHeader
        title="Register unidentified patient"
        subtitle="Creates a temporary record with a unique MRN immediately — no identity required."
      />

      <form onSubmit={handleSubmit} noValidate className="space-y-6">
        {/* Descriptive fields */}
        <div className="card space-y-5">
          <h2 className="section-title">Descriptive information</h2>
          <p className="text-xs text-charcoal-500">All fields optional — enter whatever is known at admission.</p>

          <FormField label="Placeholder name" hint="e.g. 'Unidentified Male' or a descriptor. Auto-filled if left blank.">
            <input
              className="input-field"
              value={form.placeholder_name}
              onChange={e => setForm(f => ({ ...f, placeholder_name: e.target.value }))}
              placeholder="Unidentified"
              disabled={busy}
            />
          </FormField>

          <div className="grid grid-cols-2 gap-4">
            <FormField label="Approximate age">
              <input
                className="input-field"
                type="number"
                min={0}
                max={120}
                value={form.approx_age}
                onChange={e => setForm(f => ({ ...f, approx_age: e.target.value }))}
                placeholder="e.g. 35"
                disabled={busy}
              />
            </FormField>
            <FormField label="Approximate sex">
              <select
                className="input-field"
                value={form.approx_sex}
                onChange={e => setForm(f => ({ ...f, approx_sex: e.target.value }))}
                disabled={busy}
              >
                <option value="">Unknown</option>
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
              </select>
            </FormField>
          </div>

          <FormField label="Distinguishing features" hint="Physical descriptors, clothing, medical alert items, etc.">
            <textarea
              className="input-field min-h-[80px] resize-none"
              value={form.distinguishing_features}
              onChange={e => setForm(f => ({ ...f, distinguishing_features: e.target.value }))}
              placeholder="e.g. Medical alert bracelet, tattoo on left forearm, blue jacket"
              disabled={busy}
            />
          </FormField>
        </div>

        {/* Clinical notes */}
        <div className="card space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="section-title">Initial clinical notes</h2>
              <p className="text-xs text-charcoal-500 mt-0.5">Attach immediately — no identity gate.</p>
            </div>
            <button
              type="button"
              className="btn-ghost flex items-center gap-1.5 text-sm"
              onClick={addNote}
              disabled={busy}
            >
              <Plus size={14} /> Add note
            </button>
          </div>

          <div className="space-y-3">
            {notes.map((note, i) => (
              <div key={i} className="rounded-xl border border-ivory-200 bg-ivory-50 p-4 space-y-3">
                <div className="flex items-center justify-between gap-3">
                  <select
                    className="input-field w-40 py-2 text-sm"
                    value={note.type}
                    onChange={e => setNote(i, 'type', e.target.value as NoteEntry['type'])}
                    disabled={busy}
                  >
                    {NOTE_TYPES.map(t => (
                      <option key={t.value} value={t.value}>{t.label}</option>
                    ))}
                  </select>
                  {notes.length > 1 && (
                    <button
                      type="button"
                      className="text-charcoal-400 hover:text-charcoal-600 text-xs px-2 py-1 rounded hover:bg-ivory-200 transition-colors"
                      onClick={() => removeNote(i)}
                      disabled={busy}
                    >
                      Remove
                    </button>
                  )}
                </div>
                <textarea
                  className="input-field min-h-[80px] resize-none bg-white text-sm"
                  placeholder={
                    note.type === 'vitals'    ? 'BP 120/80, HR 88, SpO₂ 97%, Temp 37.2°C…' :
                    note.type === 'injuries'  ? 'Laceration to right forehead, possible rib fracture…' :
                    note.type === 'treatment' ? 'IV access established, 500ml NS administered…' :
                    'Additional observations…'
                  }
                  value={note.content}
                  onChange={e => setNote(i, 'content', e.target.value)}
                  disabled={busy}
                />
              </div>
            ))}
          </div>
        </div>

        {apiError && (
          <div className="flex items-start gap-2 px-4 py-3 rounded-xl bg-ivory-100 border border-ivory-300">
            <AlertCircle size={14} className="text-teal-800 mt-0.5 flex-shrink-0" />
            <p className="text-sm text-charcoal-700">{apiError}</p>
          </div>
        )}

        <div className="flex justify-end gap-3">
          <button
            type="button"
            className="btn-secondary"
            onClick={() => navigate('/hospital/dashboard')}
            disabled={busy}
          >
            Cancel
          </button>
          <button type="submit" className="btn-primary flex items-center gap-2" disabled={busy}>
            {busy ? <Spinner size="sm" /> : <UserSearch size={15} />}
            {busy ? 'Creating record…' : 'Create temporary record'}
          </button>
        </div>
      </form>
    </div>
  )
}
